title: "papichulo16"
description: "blog/writeup/project site"
theme: minima

collections:
  projects:
    output: true
  blogs:
    output: true
    permalink: /blogs/:name/

plugins:
  - jekyll-feed
  - jekyll-seo-tag

